<a href="https://colab.research.google.com/github/AI-Krittaya/dataviz2025/blob/main/%E0%B8%B8%E0%B8%B8663020277_7_midterm2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ให้สืบหาฆาตรกร (10 คะแนน) และ ผู้บงการ (5 คะแนน) ในคดี ฆาตรกรรม (murder) ที่เกิดขึ้นในวันที่ 15 มกราคม 2018 ที่เมือง Pandas City โดยเริ่มจากการตรวจสอบ ข้อมูลคดีในไฟล์ crime_scene_report.csv

# นำข้อมูลเข้า

In [130]:
import pandas as pd

In [131]:
import os

In [132]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [133]:
crimescene_df = pd.read_csv('/content/drive/MyDrive/Python&Dataviz2025/Data/Exam Data DataViz2025/crime_scene_report.csv')
drivers_license_df = pd.read_csv('/content/drive/MyDrive/Python&Dataviz2025/Data/Exam Data DataViz2025/drivers_license.csv')
facebook_event_checkin_df = pd.read_csv('/content/drive/MyDrive/Python&Dataviz2025/Data/Exam Data DataViz2025/facebook_event_checkin.csv')
get_fit_now_check_in_df = pd.read_csv('/content/drive/MyDrive/Python&Dataviz2025/Data/Exam Data DataViz2025/get_fit_now_check_in.csv')
get_fit_now_member_df = pd.read_csv('/content/drive/MyDrive/Python&Dataviz2025/Data/Exam Data DataViz2025/get_fit_now_member.csv')
income_df = pd.read_csv('/content/drive/MyDrive/Python&Dataviz2025/Data/Exam Data DataViz2025/income.csv')
interview_df = pd.read_csv('/content/drive/MyDrive/Python&Dataviz2025/Data/Exam Data DataViz2025/interview.csv')
person_df = pd.read_csv('/content/drive/MyDrive/Python&Dataviz2025/Data/Exam Data DataViz2025/person.csv')



In [189]:
crimescene_df

date     type  \
0     20180115  robbery   
1     20180115   murder   
2     20180115   murder   
3     20180215   murder   
4     20180215   murder   
...        ...      ...   
1223  20180430  bribery   
1224  20180430    fraud   
1225  20180430  assault   
1226  20180501  assault   
1227  20180115   murder   

                                                                                                                                                                                    description  \
0                                                                                                                                             A Man Dressed as Spider-Man Is on a Robbery Spree   
1                                                                                                                                                             Life? Dont talk to me about life.   
2                                                                                                                                           Mama, I killed a man, put a gun against his head...   
3                                                                                                                                                                    REDACTED REDACTED REDACTED   
4                                                                                                                                       Someone killed the guard! He took an arrow to the knee!   
...                                                                                                                                                                                         ...   
1223                                                                                                                                                                                         \n   
1224                                                                                                                                                          ‘Why not?’ said the March Hare.\n   
1225                                                                                                                                                                                         \n   
1226                                                                                                                 be NO mistake about it: it was neither more nor less than a pig, and she\n   
1227  Security footage shows that there were 2 witnesses. The first witness lives at the last house on "Northwestern Dr". The second witness, named Annabel, lives somewhere on "Franklin Ave".   

              city  
0              NYC  
1           Albany  
2             Reno  
3      Pandas City  
4      Pandas City  
...            ...  
1223  Garden Grove  
1224         Houma  
1225       Fontana  
1226       Trenton  
1227   Pandas City  

[1228 rows x 4 columns]

In [188]:
display(crimescene_df.isnull())

date   type  description   city
0     False  False        False  False
1     False  False        False  False
2     False  False        False  False
3     False  False        False  False
4     False  False        False  False
...     ...    ...          ...    ...
1223  False  False        False  False
1224  False  False        False  False
1225  False  False        False  False
1226  False  False        False  False
1227  False  False        False  False

[1228 rows x 4 columns]

# คดีวันที่ 15 มกราคม 2018 ที่เมือง Pandas City

In [135]:
pandas_city_crimes = crimescene_df[(crimescene_df['date'] == 20180115) & (crimescene_df['city'] == 'Pandas City')]
pandas_city_crimes

date     type  \
11    20180115  assault   
12    20180115  assault   
1227  20180115   murder   

                                                                                                                                                                                    description  \
11                                                                                                                  Hamilton: Lee, do you yield? Burr: You shot him in the side! Yes he yields!   
12                                                                                                                                                                             Report Not Found   
1227  Security footage shows that there were 2 witnesses. The first witness lives at the last house on "Northwestern Dr". The second witness, named Annabel, lives somewhere on "Franklin Ave".   

             city  
11    Pandas City  
12    Pandas City  
1227  Pandas City

# หาพยาน

In [136]:
pd.set_option('display.max_colwidth', None)
display(pandas_city_crimes['description'])

11                                                                                                                    Hamilton: Lee, do you yield? Burr: You shot him in the side! Yes he yields!
12                                                                                                                                                                               Report Not Found
1227    Security footage shows that there were 2 witnesses. The first witness lives at the last house on "Northwestern Dr". The second witness, named Annabel, lives somewhere on "Franklin Ave".
Name: description, dtype: object

Security footage shows that there were **2 witnesses**. The** first** witness lives at the **last house** on **"Northwestern Dr"**. The second witness, named **Annabel**, lives somewhere on **"Franklin Ave"**.


In [137]:
person_df.head()

id                 name  license_id  address_number address_street_name  \
0  10000   Christoper Peteuil      993845             624        Bankhall Ave   
1  10007  Kourtney Calderwood      861794            2791       Gustavus Blvd   
2  10010            Muoi Cary      385336             741     Northwestern Dr   
3  10016          Era Moselle      431897            1987       Wood Glade St   
4  10025         Trena Hornby      550890             276       Daws Hill Way   

         ssn  
0  747714076  
1  477972044  
2  828638512  
3  614621061  
4  223877684

In [138]:
person_df.head()

id                 name  license_id  address_number address_street_name  \
0  10000   Christoper Peteuil      993845             624        Bankhall Ave   
1  10007  Kourtney Calderwood      861794            2791       Gustavus Blvd   
2  10010            Muoi Cary      385336             741     Northwestern Dr   
3  10016          Era Moselle      431897            1987       Wood Glade St   
4  10025         Trena Hornby      550890             276       Daws Hill Way   

         ssn  
0  747714076  
1  477972044  
2  828638512  
3  614621061  
4  223877684

## พยานคนที่1

In [161]:
person1_df = person_df[(person_df['address_street_name'] == 'Northwestern Dr')]
display(person1_df)

id                  name  license_id  address_number  \
2     10010             Muoi Cary      385336             741   
282   12711        Norman Apolito      667757             599   
499   14887        Morty Schapiro      118009            4919   
528   15171          Weldon Penso      336999             311   
811   17729        Lasonya Wildey      439686            3824   
904   18376              Josh Shi      653712            1091   
1021  19420           Cody Schiel      890431            3524   
1338  22239         Dusty Sigafus      710517            1125   
1426  23044          Val Portlock      924989            3143   
1522  23960  Kristopher Lagerberg      658777            1392   
1686  25615         Olevia Morena      388477             812   
1812  26758      Angelena Billman      942074             629   
1981  28360        Rashad Cascone      924517            3212   
2131  29608       Willetta Lurvey      800568            1028   
2535  33415         Homer Simpson      108392             981   
2620  34155      Allyson Lazenson      814209            2840   
2635  34352    Vincenza Burkhardt      436470            2512   
2871  36378        Freddie Ellzey      267882            3449   
3237  39688            Abe Roeker      537445             689   
3316  40336       Fredia Billeter      251082             404   
3368  40760          Renata Faver      976650             745   
3743  44004           Alison Eska      327797            2951   
3795  44542        Ivory Mcgrevey      873842             897   
4595  51114     Christena Saffell      814284            3055   
4643  51552           Bonita Knie      764124            1726   
4806  53076           Boris Bijou      664914            3327   
4871  53699      Christian Pagano      628433            2585   
4886  53890        Sophie Tiberio      957671            3755   
4956  54564         Sammie Sengun      217286            2590   
5024  55130        Shiloh Huntoon      472118             951   
5450  59307          Cyril Yongue      753524            2903   
6476  68690            Yer Modest      852404            3046   
6698  70485     Andera Kostelecky      354822            1252   
6865  71924        Laurie Scronce      774116            1418   
6877  72076     Courtney Bordeaux      324614            1707   
7040  73368        Torie Thalmann      773862            3697   
7296  75484          Del Tacderen      447887             607   
7888  80921       Donovan Yackley      222395            2386   
7902  81052     Calvin Czelusniak      471483            1516   
7993  81885         Kurtis Masuda      934201            2108   
8369  85280             Donn Duin      569122             540   
8608  87456   Leonora Wolfsberger      215868            3483   
8720  88423           Teri Ehrich      510876            1879   
8888  89906       Kinsey Erickson      510019             309   
8939  90397     Dionna Kranwinkle      797260            2678   
9272  93509        Emmitt Aceuedo      916706            3491   
9569  96178           Galina Khuu      450248            2183   
9609  96595         Coretta Cubie      303645            3631   
9841  98593           Jonah Toner      578982            2947   
9991  99826          Ivy Kazarian      994470             892   

     address_street_name        ssn  
2        Northwestern Dr  828638512  
282      Northwestern Dr  778264744  
499      Northwestern Dr  111564949  
528      Northwestern Dr  131379495  
811      Northwestern Dr  917817122  
904      Northwestern Dr  193899001  
1021     Northwestern Dr  947110049  
1338     Northwestern Dr  724386723  
1426     Northwestern Dr  100593316  
1522     Northwestern Dr  492912529  
1686     Northwestern Dr  962831331  
1812     Northwestern Dr  341854756  
1981     Northwestern Dr  838907424  
2131     Northwestern Dr  843751378  
2535     Northwestern Dr  871392019  
2620     Northwestern Dr  991150469  
2635     Northwestern Dr  197913046  
2871     

In [168]:
last_house_northwestern_df = person1_df.sort_values(by='address_number', ascending=False).head(1)
display(last_house_northwestern_df)

id            name  license_id  address_number address_street_name  \
499  14887  Morty Schapiro      118009            4919     Northwestern Dr   

           ssn  
499  111564949

## พยานคนที่ 2

In [176]:
person2_df = person_df[(person_df['address_street_name'] == 'Franklin Ave')]
display(person2_df)

id                 name  license_id  address_number  \
235   12207       Wilmer Wolever      509484             139   
665   16371       Annabel Miller      490173             103   
807   17683        Johnnie Schee      968887            1277   
936   18651        Carleen Etoll      356746              22   
1377  22636       Zachary Ybarbo      768359             785   
1608  24737           Gema Nantz      273410            3968   
2236  30654      Clarita Rickels      418084            2254   
2427  32264       Shelby Dezeeuw      735415            1391   
2584  33793         Amado Mattan      161915              99   
2661  34592    Cordell Lindamood      592762            3657   
2864  36328         Domenic Laun      971080            3809   
2877  36400         Noe Pancoast      895755            3443   
3009  37616     Katelyn Schwerin      430143             332   
4086  46827         Bev Billiter      643591            2316   
4708  52059        Jordan Pelton      686854            2786   
4709  52075             Ezra Phy      928109             384   
4714  52121       Yelena Whitler      427830            3185   
4990  54817          Guy Bustard      213929             591   
4998  54896        Patty Wamsley      688488            1097   
5142  56142       William Shiver      741336            1926   
5233  57051        Lavette Koehl      137365            2284   
5497  59746        Ronny Gumbert      469722            3197   
5641  60944        Ricki Bidding      443364            2072   
5653  61001      Laurine Bousman      197150             247   
5709  61437     Colette Hollomon      661377             453   
5810  62292       Isaiah Holsten      913856             747   
5829  62520      Mariah Lepetich      450447            3086   
6326  67292       Renita Roperto      801041             625   
6597  69719        Hope Arzabala      311724             841   
6641  70050   Whitney Herkenratt      138462            3445   
7300  75510  Sebastian Ramnarase      333188            1127   
7357  76128         Ressie Razze      633497            1199   
7574  78170          Graig Summy      192325            3387   
7610  78408         Dante Eschen      218173            3447   
7637  78658        Blake Chrones      310242            2014   
7658  78830        Candice Train      814779            3255   
8120  83003       Wilmer Casella      672050            3564   
8203  83754          Maria Walsh      201334            2716   
8302  84531       Edgar Mendieta      315790            3881   
8624  87521          Moses Ikerd      638991            2283   
8783  88966            Raul Eads      570927            2066   
9322  93947        Omer Andreoni      605718              13   
9462  95119            Hong Lisa      825828             375   
9756  97913       Cameron Dilick      971988            2954   
9864  98744        Jordan Myntti      256116            3104   

     address_street_name        ssn  
235         Franklin Ave  636825374  
665         Franklin Ave  318771143  
807         Franklin Ave  815977821  
936         Franklin Ave  193369255  
1377        Franklin Ave  285346605  
1608        Franklin Ave  180545802  
2236        Franklin Ave  714941023  
2427        Franklin Ave  143197463  
2584        Franklin Ave  125205748  
2661        Franklin Ave  509890333  
2864        Franklin Ave  825329637  
2877        Franklin Ave  732212073  
3009        Franklin Ave  392365033  
4086        Franklin Ave  940192302  
4708        Franklin Ave  676224073  
4709        Franklin Ave  176404498  
4714        Franklin Ave  115106155  
4990        Franklin Ave  820850670  
4998        Franklin Ave  725272037  
5142        Franklin Ave  219913461  
5233        Franklin Ave  776046786  
5497        Franklin Ave  561067477  
5641        Franklin Ave  614976330  
5653        Franklin Ave  431360364  
5709        Franklin Ave  314956038  
5810        Franklin Ave  995368430  
5829        Franklin Ave  797745632  


16371	Annabel Miller	490173	103	Franklin Ave	318771143

# interview

In [178]:
interview_df

person_id  \
0         28508   
1         63713   
2         86208   
3         35267   
4         33856   
...         ...   
4986      37357   
4987      10206   
4988      14887   
4989      16371   
4990      67318   

                                                                                                                                                                                                                                              transcript  
0                                                                                                                                                                                                                    ‘I deny it!’ said the March Hare.\n  
1                                                                                                                                                                                                                                                     \n  
2                                                                                                                                                                                                          way, and the whole party swam to the shore.\n  
3                                                                                                                                                                                lessons in here? Why, there’s hardly room for YOU, and no room at all\n  
4                                                                                                                                                                                                                                                     \n  
...                                                                                                                                                                                                                                                  ...  
4986                                                                                                                                                                                Alice did not wish to offend the Dormouse again, so she began very\n  
4987                                                                                                                                                                          time,’ she said, ‘than waste it in asking riddles that have no answers.’\n  
4988                     I heard a gunshot and then saw a man run out. He had a "Get Fit Now Gym" bag. The membership number on the bag started with "48Z". Only gold members have those bags. The man got into a car with a plate that included "H42W".  
4989                                                                                                                               I saw the murder happen, and I recognized the killer from my gym when I was working out last week on January the 9th.  
4990  I was hired by a woman with a lot of money. I don't know her name but I know she's around 5'5" (65") or 5'7" (67"). She has red hair and she drives a Tesla Model S. I know that she attended the SQL Symphony Concert 3 times in December 2017.\n  

[4991 rows x 2 columns]

In [209]:
display(interview_df[(interview_df['person_id'] == 14887) | (interview_df['person_id'] == 16371)])

person_id  \
4988      14887   
4989      16371   

                                                                                                                                                                                                                           transcript  
4988  I heard a gunshot and then saw a man run out. He had a "Get Fit Now Gym" bag. The membership number on the bag started with "48Z". Only gold members have those bags. The man got into a car with a plate that included "H42W".  
4989                                                                                                            I saw the murder happen, and I recognized the killer from my gym when I was working out last week on January the 9th.

14887	I heard a gunshot and then saw a man run out. He had a "Get Fit Now Gym" bag. The membership number on the bag started with "48Z". Only gold members have those bags. The man got into a car with a plate that included "H42W".

"ฉันได้ยินเสียงปืนแล้วเห็นผู้ชายคนหนึ่งวิ่งออกมา เขามีถุงยิม 'Get Fit Now Gym' หมายเลขสมาชิกบนถุงเริ่มต้นด้วย '48Z' เฉพาะสมาชิก Gold เท่านั้นที่มีถุงเหล่านี้ ผู้ชายคนนั้นขึ้นรถยนต์ที่มีป้ายทะเบียนที่มี 'H42W' อยู่ด้วย"

16371	I saw the murder happen, and I recognized the killer from my gym when I was working out last week on January the 9th.

"ฉันเห็นการฆาตกรรมเกิดขึ้น และฉันจำฆาตกรได้จากยิมของฉัน ตอนที่ฉันไปออกกำลังกายเมื่อสัปดาห์ที่แล้วในวันที่ 9 มกราคม"


# ผู้ต้องสงสัย

In [182]:
get_fit_now_member_df

id  person_id                name  membership_start_date  \
0    NL318      65076     Everette Koepke               20170926   
1    AOE21      39426        Noe Locascio               20171005   
2    2PN28      63823  Jeromy Heitschmidt               20180215   
3    0YJ24      80651      Waneta Wellard               20171206   
4    3A08L      32858        Mei Bianchin               20170401   
..     ...        ...                 ...                    ...   
179  2V137      41693      Wendell Dulany               20171219   
180  4KB72      79110          Emile Hege               20170522   
181  48Z7A      28819        Joe Germuska               20160305   
182  48Z55      67318       Jeremy Bowers               20160101   
183  90081      16371      Annabel Miller               20160208   

    membership_status  
0                gold  
1             regular  
2              silver  
3                gold  
4              silver  
..                ...  
179            silver  
180           regular  
181              gold  
182              gold  
183              gold  

[184 rows x 5 columns]

In [180]:
get_fit_now_member_df[(get_fit_now_member_df['membership_status'] == 'gold') & (get_fit_now_member_df['id'].str.startswith('48Z'))]

id  person_id           name  membership_start_date membership_status
181  48Z7A      28819   Joe Germuska               20160305              gold
182  48Z55      67318  Jeremy Bowers               20160101              gold

--------------------------------

In [181]:
get_fit_now_check_in_df

membership_id  check_in_date  check_in_time  check_out_time
0            NL318       20180212            329             365
1            NL318       20170811            469             920
2            NL318       20180429            506             554
3            NL318       20180128            124             759
4            NL318       20171027            418            1019
...            ...            ...            ...             ...
2698         4KB72       20170422           1016            1114
2699         4KB72       20170630            408             885
2700         48Z7A       20180109           1600            1730
2701         48Z55       20180109           1530            1700
2702         90081       20180109           1600            1700

[2703 rows x 4 columns]

In [185]:
get_fit_now_check_in_df[(get_fit_now_check_in_df)['check_in_date'] == 20180109]

membership_id  check_in_date  check_in_time  check_out_time
113          X0643       20180109            957            1164
889          UK1F2       20180109            344             518
1329         XTE42       20180109            486            1124
1446         1AE2H       20180109            461             944
1703         6LSTG       20180109            399             515
2137         7MWHJ       20180109            273             885
2435         GE5Q8       20180109            367             959
2700         48Z7A       20180109           1600            1730
2701         48Z55       20180109           1530            1700
2702         90081       20180109           1600            1700

In [186]:
drivers_license_df

id  age  height eye_color hair_color  gender plate_number  \
0      100280   72      57     brown        red    male       P24L4U   
1      100460   63      72     brown      brown  female       XF02T6   
2      101029   62      74     green      green  female       VKY5KR   
3      101198   43      54     amber      brown  female       Y5NZ08   
4      101255   18      79      blue       grey  female       5162Z1   
...       ...  ...     ...       ...        ...     ...          ...   
10002  999923   19      77     amber      black  female       5L0ZI4   
10003  999940   71      61     green      green    male       1B8QN8   
10004  999981   67      69     brown       blue  female       1684K3   
10005  999986   49      58     green       grey    male       F8F64H   
10006  999993   18      63     black      black  female       6UZO2O   

         car_make    car_model  
0           Acura          MDX  
1        Cadillac          SRX  
2           Scion           xB  
3          Nissan        Rogue  
4           Lexus           GS  
...           ...          ...  
10002         GMC  Sierra 3500  
10003  Mitsubishi      Eclipse  
10004  Land Rover          LR2  
10005       Lexus           LS  
10006    Cadillac      DeVille  

[10007 rows x 9 columns]

In [242]:
display(drivers_license_df[drivers_license_df['plate_number'].str.contains('H42W')])

id  age  height eye_color hair_color  gender plate_number  \
915   183779   21      65      blue     blonde  female       H42W0X   
3529  423327   30      70     brown      brown    male       0H42W2   
6240  664760   21      71     black      black    male       4H42WR   

       car_make car_model  
915      Toyota     Prius  
3529  Chevrolet  Spark LS  
6240     Nissan    Altima

##สงสัย

id 67318,	Jeremy Bowers

# หาผู้บงการ

interview ผู้ต้องสงสัย

In [210]:
interview_df[(interview_df['person_id'])== 28819]

Empty DataFrame
Columns: [person_id, transcript]
Index: []

In [211]:
interview_df[(interview_df['person_id'])== 67318]

person_id  \
4990      67318   

                                                                                                                                                                                                                                              transcript  
4990  I was hired by a woman with a lot of money. I don't know her name but I know she's around 5'5" (65") or 5'7" (67"). She has red hair and she drives a Tesla Model S. I know that she attended the SQL Symphony Concert 3 times in December 2017.\n

"ฉันถูกจ้างโดยผู้หญิงคนหนึ่งที่มี**เงินเยอะ** ฉันไม่รู้ชื่อของเธอ แต่ฉันรู้ว่าเธอสูงประมาณ 5'5" (**65 นิ้ว**) หรือ 5'7" (**67 นิ้ว**) เธอมี**ผมสีแดง**และขับรถ **Tesla Model S** ฉันรู้ว่าเธอไปร่วมงาน **SQL Symphony Concert 3 ครั้งในเดือนธันวาคม 2017**"

In [201]:
drivers_license_df

id  age  height eye_color hair_color  gender plate_number  \
0      100280   72      57     brown        red    male       P24L4U   
1      100460   63      72     brown      brown  female       XF02T6   
2      101029   62      74     green      green  female       VKY5KR   
3      101198   43      54     amber      brown  female       Y5NZ08   
4      101255   18      79      blue       grey  female       5162Z1   
...       ...  ...     ...       ...        ...     ...          ...   
10002  999923   19      77     amber      black  female       5L0ZI4   
10003  999940   71      61     green      green    male       1B8QN8   
10004  999981   67      69     brown       blue  female       1684K3   
10005  999986   49      58     green       grey    male       F8F64H   
10006  999993   18      63     black      black  female       6UZO2O   

         car_make    car_model  
0           Acura          MDX  
1        Cadillac          SRX  
2           Scion           xB  
3          Nissan        Rogue  
4           Lexus           GS  
...           ...          ...  
10002         GMC  Sierra 3500  
10003  Mitsubishi      Eclipse  
10004  Land Rover          LR2  
10005       Lexus           LS  
10006    Cadillac      DeVille  

[10007 rows x 9 columns]

In [265]:
display(drivers_license_df[(drivers_license_df['gender'] == 'female') &
  (drivers_license_df['hair_color'] == 'red') &
  (drivers_license_df['car_make'] == 'Tesla') &
  (drivers_license_df['car_model'] == 'Model S')]
        )

id  age  height eye_color hair_color  gender plate_number car_make  \
1105  202298   68      66     green        red  female       500123    Tesla   
2054  291182   65      66      blue        red  female       08CM64    Tesla   
9078  918773   48      65     black        red  female       917UU3    Tesla   

     car_model  
1105   Model S  
2054   Model S  
9078   Model S

In [266]:
person_df[(person_df['license_id'].isin([202298, 291182, 918773]))]

id              name  license_id  address_number address_street_name  \
7664  78881          Red Korb      918773             107         Camerata Dr   
8977  90700     Regina George      291182             332           Maple Ave   
9985  99716  Miranda Priestly      202298            1883          Golden Ave   

            ssn  
7664  961388910  
8977  337169072  
9985  987756388

In [271]:
display(facebook_event_checkin_df[facebook_event_checkin_df['person_id'].isin([78881,907000,99716])])

person_id  event_id            event_name      date
20006      99716      1143  SQL Symphony Concert  20171206
20007      99716      1143  SQL Symphony Concert  20171212
20008      99716      1143  SQL Symphony Concert  20171229

In [272]:
income_df[(income_df['ssn'] == 987756388)]

ssn  annual_income
7422  987756388         310000

## ผู้บงการ

In [273]:
person_df[(person_df['id'] == 99716)]

id              name  license_id  address_number address_street_name  \
9985  99716  Miranda Priestly      202298            1883          Golden Ave   

            ssn  
9985  987756388

# สรุป

**ฆาตกร คือ Jeremy Bowers (id 67318)**

เบาะแสที่นำไปสู่ข้อสรุปนี้ คือ
* เขาอยู่ที่ยิมในวันที่ 9 มกราคม 2018 ตามที่พยาน Annabel กล่าวไว้
* เขามีสมาชิกแบบ Gold ที่ Get Fit Now Gym และหมายเลขสมาชิกของเขาขึ้นต้นด้วย "48Z"
* เขาขับรถยนต์ที่มีป้ายทะเบียนมีส่วนประกอบของ "H42W"

**ผู้บงการ คือ Miranda Priestly (id 99716)**

เบาะแสที่นำไปสู่ข้อสรุปนี้ คือ
คำให้การของผู้ต้องสงสัย (Jeremy Bowers)
* เป็นผู้หญิงผมแดง สูงประมาณ 65 หรือ 67 นิ้ว (จริง ๆ สูง 66 นิ้ว)
* มีเงินเยอะ
* ขับรถ Tesla Model S
* ไปงาน SQL Symphony Concert 3 ครั้งในเดือนธันวาคม 2017
